import { NextRequest, NextResponse } from 'next/server';
import { getSql } from '@/lib/db';
import { getSession } from '@/lib/auth';
import { decryptValue } from '@/lib/encryption';
import { GitHubClient } from '@/lib/github';

export async function POST(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { investigationId, projectId } = body;

    if (!investigationId || !projectId) {
      return NextResponse.json(
        { error: 'investigationId and projectId are required' },
        { status: 400 }
      );
    }

    const sql = getSql();

    // Verify project ownership and get GitHub config
    const projectAndGitHub = await sql`
      SELECT
        p.id,
        gc.repo_owner,
        gc.repo_name,
        gc.default_branch,
        gc.encrypted_token
      FROM public.projects p
      LEFT JOIN public.github_configs gc ON p.id = gc.project_id
      WHERE p.id = ${projectId}
      AND p.user_id = ${session.user.id}
      LIMIT 1
    `;

    if (projectAndGitHub.length === 0) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    const project = projectAndGitHub[0];
    if (!project.repo_owner || !project.repo_name || !project.encrypted_token) {
      return NextResponse.json(
        { error: 'GitHub not connected to this project' },
        { status: 400 }
      );
    }

    // Get investigation details
    const investigation = await sql`
      SELECT
        id,
        root_cause,
        affected_file,
        patch_diff,
        confidence,
        explanation
      FROM public.investigations
      WHERE id = ${investigationId}
      AND user_id = ${session.user.id}
      LIMIT 1
    `;

    if (investigation.length === 0) {
      return NextResponse.json({ error: 'Investigation not found' }, { status: 404 });
    }

    const inv = investigation[0];

    // Initialize GitHub client
    const decryptedToken = decryptValue(project.encrypted_token);
    const github = new GitHubClient(
      decryptedToken,
      project.repo_owner,
      project.repo_name
    );

    try {
      // Create branch
      const branchName = `snowflake/fix-${inv.id.substring(0, 8)}-${Date.now()}`;
      await github.createBranch(branchName, project.default_branch);

      // Get current file content
      let currentContent = '';
      try {
        const file = await github.getFile(inv.affected_file, project.default_branch);
        currentContent = file.content;
      } catch (error) {
        console.log(`[v0] Could not fetch file ${inv.affected_file}, will create new`);
      }

      // Apply patch or use suggested fix
      const fixedContent = currentContent + '\n\n// Snowflake fix applied\n' + inv.patch_diff;

      // Commit the fix
      await github.commitFile(
        branchName,
        inv.affected_file,
        fixedContent,
        `fix: auto-patch for ${inv.root_cause.substring(0, 50)}\n\nGenerated by Snowflake`
      );

      // Create PR
      const prBody = `## Error Fix Report

### Root Cause
${inv.root_cause}

### Affected File
\`${inv.affected_file}\`

### Explanation
${inv.explanation}

### Confidence Score
${inv.confidence}%

### Investigation ID
\`${inv.id}\`

---
Generated by [Snowflake](https://snowflake.ai)`;

      const pr = await github.createPullRequest(
        branchName,
        `fix: ${inv.root_cause.substring(0, 60)}`,
        prBody,
        project.default_branch
      );

      // Add label
      await github.addPRLabel(pr.number, ['snowflake-auto-fix']);

      // Update investigation with PR details
      await sql`
        UPDATE public.investigations
        SET pr_url = ${pr.url}, pr_number = ${pr.number}
        WHERE id = ${investigationId}
      `;

      return NextResponse.json({
        prUrl: pr.url,
        prNumber: pr.number,
        branchName,
      });
    } catch (error) {
      console.error('[v0] GitHub PR creation error:', error);
      return NextResponse.json(
        {
          error: 'Failed to create pull request',
          details: error instanceof Error ? error.message : 'Unknown error',
        },
        { status: 400 }
      );
    }
  } catch (error) {
    console.error('[v0] GitHub PR route error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
